CREATE TABLE RedditSubmissions (
author VARCHAR(20),
author_created_utc INT(10) ,
author_flair_css_class varchar(4),
author_flair_text varchar(4),
author_fullname varchar(10),
created_utc int(10),
domain varchar(25),
full_link varchar(1000),
gilded int(1),
id int(8),
is_self bool,
media_embed varchar(4),
num_comments int(6),
over_18 bool,
permalink varchar(2000),
retrieved_on int(10),
score int(5),
secure_media_embed varchar(4), 
selftext varchar(40000),
stickied bool,
subreddit varchar(20),
subreddit_id varchar(8),
thumbnail varchar(20),
title varchar(1000),
url varchar(1000),
distinguished varchar(50),
post_hint varchar(20),
preview varchar (1000),
media varchar(3000),
secure_media varchar(3000),
edited int(10),
lockedcol varchar(9),
banned_by,
link_flair_css_class,
link_flair_text,
contest_mode,
spoiler,
brand_safe,
suggested_sort,
author_cakeday,
thumbnail_height,
thumbnail_width,
is_video,
approved_at_utc,
banned_at_utc,
can_mod_post,
view_count,
parent_whitelist_status,
whitelist_status,
is_crosspostable,
num_crossposts,
pinned,
is_reddit_media_domain,
crosspost_parent,
crosspost_parent_list,
subreddit_type,
author_flair_richtext,
author_flair_type,
link_flair_richtext,
link_flair_text_color,
link_flair_type,
rte_mode,
link_flair_background_color,
link_flair_template_id,
author_flair_background_color,
author_flair_text_color,
send_replies,
no_follow,
subreddit_subscribers,
is_original_content,
previous_visits,
wls,
pwls,
archived,
author_flair_template_id,
author_patreon_flair,
can_gild,
category,
content_categories,
gildings,
hidden,
is_meta,
is_robot_indexable,
media_only,
quarantine,
removal_reason,
subreddit_name_prefixed,
author_id,
all_awardings,
allow_live_comments,
author_premium,
awarders,
total_awards_received,
treatment_tags,
upvote_ratio,
removed_by_category,
url_overridden_by_dest,
media_metadata,
updated_utc,
event_end,
event_is_live,
event_start,
steward_reports,
discussion_type,
og_description,
og_title,
removed_by,
poll_data,
collections,
top_awarded_type,
is_gallery,
gallery_data,
is_created_from_ads_ui,
author_is_blocked
);